Update patch set 2
Patch Set 2:

This change broke a libcore test:

 org.apache.harmony.security.tests.java.security.DigestInputStream2Test#test_onZ
    java.lang.RuntimeException: Unable to copy EVP_MD_CTX
    	at com.android.org.conscrypt.NativeCrypto.EVP_MD_CTX_copy(Native Method)
    	at com.android.org.conscrypt.OpenSSLMessageDigestJDK.clone(OpenSSLMessageDigestJDK.java:200)
    	at java.security.MessageDigest$MessageDigestImpl.clone(MessageDigest.java:428)
    	at org.apache.harmony.security.tests.java.security.DigestInputStream2Test.test_onZ(DigestInputStream2Test.java:62)
  org.apache.harmony.security.tests.java.security.DigestInputStream2Test#test_onZ FAIL (EXEC_FAILED)

Patch-set: 2
Reviewer: Gerrit User 1038443 <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0