Update patch set 2
Patch Set 2:

Looks like it's because this test is linking against a jarjar copy of Bouncycastle. The ones built into the platform are com.android.org.bouncycastle.

ERROR: external/conscrypt/openjdk/src/test/java/libcore/java/security/TestKeyStore.java:19.8: The import org.bouncycastle cannot be resolved

Patch-set: 2