Revert "Add method to delete extension from a certificate"
Leads to build failures:

external/conscrypt/src/main/native/org_conscrypt_NativeCrypto.cppexternal/conscrypt/src/main/native/org_conscrypt_NativeCrypto.cpp::69356935::3232::  errorerror: : use of undeclared identifier 'X509_get_cert_info'use of undeclared identifier 'X509_get_cert_info'

        X509_CINF_set_modified(X509_get_cert_info(x509));
                               ^
        X509_CINF_set_modified(X509_get_cert_info(x509));
                               ^

This reverts commit 64c85650fce6132ef66be9f7750cf28674cd65d7.

Change-Id: I773666da5e71717537342a16550ebfc812531afa